.PHONY: clean All

All:
	@echo "----------Building project:[ StaticGlobal - Debug ]----------"
	@cd "StaticGlobal" && "$(MAKE)" -f  "StaticGlobal.mk"
clean:
	@echo "----------Cleaning project:[ StaticGlobal - Debug ]----------"
	@cd "StaticGlobal" && "$(MAKE)" -f  "StaticGlobal.mk" clean
