.PHONY: clean All

All:
	@echo "----------Building project:[ TreeRecursion - Debug ]----------"
	@cd "TreeRecursion" && "$(MAKE)" -f  "TreeRecursion.mk"
clean:
	@echo "----------Cleaning project:[ TreeRecursion - Debug ]----------"
	@cd "TreeRecursion" && "$(MAKE)" -f  "TreeRecursion.mk" clean
