.PHONY: clean All

All:
	@echo "----------Building project:[ Array_ADT_1 - Debug ]----------"
	@cd "Array_ADT_1" && "$(MAKE)" -f  "Array_ADT_1.mk"
clean:
	@echo "----------Cleaning project:[ Array_ADT_1 - Debug ]----------"
	@cd "Array_ADT_1" && "$(MAKE)" -f  "Array_ADT_1.mk" clean
